USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DEVELOPER;
GRANT ROLE DEVELOPER TO USER ALWAYS;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS DCWP_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS DCWP_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS DCWP_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS DCWP_ANALYTICS.MART;

GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE DEVELOPER;
GRANT USAGE ON DATABASE DCWP_ANALYTICS TO ROLE DEVELOPER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DCWP_ANALYTICS TO ROLE DEVELOPER;
GRANT USAGE ON SCHEMA DCWP_ANALYTICS.STAGING TO ROLE DEVELOPER;
GRANT CREATE DYNAMIC TABLE ON SCHEMA DCWP_ANALYTICS.STAGING TO ROLE DEVELOPER;
GRANT USAGE ON SCHEMA DCWP_ANALYTICS.MART TO ROLE DEVELOPER;
GRANT CREATE DYNAMIC TABLE ON SCHEMA DCWP_ANALYTICS.MART TO ROLE DEVELOPER;

GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA DCWP_ANALYTICS.RAW TO ROLE DEVELOPER;
USE ROLE SECURITYADMIN;

GRANT SELECT ON DYNAMIC TABLE DCWP_ANALYTICS.STAGING.DCWP_L1   TO ROLE DEVELOPER;
GRANT SELECT ON DYNAMIC TABLE DCWP_ANALYTICS.MART.DCWP_SUMMARY TO ROLE DEVELOPER;

GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA DCWP_ANALYTICS.STAGING TO ROLE DEVELOPER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA DCWP_ANALYTICS.MART    TO ROLE DEVELOPER;
USE ROLE DEVELOPER;
USE WAREHOUSE WH_DEV;
USE DATABASE DCWP_ANALYTICS;
