USE ROLE DEVELOPER;
USE WAREHOUSE WH_DEV;
USE DATABASE DCWP_ANALYTICS;
USE SCHEMA RAW;
CREATE OR REPLACE FILE FORMAT CSV_DCWP
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null');

  CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>';
  STORAGE_ALLOWED_LOCATIONS = ('s3://dcwp-complaints-data-2025/');



DESC INTEGRATION S3_INT;

USE ROLE ACCOUNTADMIN;

ALTER STORAGE INTEGRATION S3_INT
  SET STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>';

GRANT USAGE ON INTEGRATION S3_INT TO ROLE DEVELOPER;



CREATE OR REPLACE STAGE S3_INGEST
  URL='s3://dcwp-complaints-data-2025/'
  STORAGE_INTEGRATION = S3_INT
  FILE_FORMAT = CSV_DCWP;

LIST @RAW.S3_INGEST;

SELECT $1, $2, $3, $4
FROM @RAW.S3_INGEST/Archived_Consumer_Services_Mediated_Complaints_07142023.csv
  (FILE_FORMAT => 'RAW.CSV_DCWP')

LIMIT 5;
