

CREATE OR REPLACE TABLE RAW.DCWP_COMPLAINTS (
  BUSINESS_NAME             VARCHAR,
  INDUSTRY                  VARCHAR,
  COMPLAINT_TYPE            VARCHAR,
  MEDIATION_START_DATE      DATE,
  MEDIATION_CLOSE_DATE      DATE,
  COMPLAINT_RESULT          VARCHAR,
  SATISFACTION              VARCHAR,
  RESTITUTION               FLOAT,
  BUSINESS_BUILDING         VARCHAR,
  BUSINESS_STREET           VARCHAR,
  BUILDING_ADDRESS_UNIT     VARCHAR,
  BUSINESS_CITY             VARCHAR,
  BUSINESS_STATE            VARCHAR,
  BUSINESS_ZIP              VARCHAR,
  COMPLAINANT_ZIP           VARCHAR,
  LONGITUDE                 FLOAT,
  LATITUDE                  FLOAT
);

COPY INTO RAW.DCWP_COMPLAINTS
FROM @RAW.S3_INGEST/Archived_Consumer_Services_Mediated_Complaints_07142023.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_DCWP', DATE_FORMAT = 'MM/DD/YYYY')
ON_ERROR = 'CONTINUE';



-- how many rows loaded
SELECT COUNT(*) AS ROWS_LOADED FROM RAW.DCWP_COMPLAINTS;

-- sample a few rows
SELECT * FROM RAW.DCWP_COMPLAINTS LIMIT 10;

-- quick sanity checks on dates/geo
SELECT
  MIN(MEDIATION_START_DATE) AS MIN_START,
  MAX(MEDIATION_START_DATE) AS MAX_START,
  COUNT_IF(LONGITUDE IS NULL OR LATITUDE IS NULL) AS NULL_GEO,
  COUNT_IF(RESTITUTION IS NULL) AS NULL_RESTITUTION
FROM RAW.DCWP_COMPLAINTS;