USE ROLE DEVELOPER;
USE WAREHOUSE WH_DEV;
USE DATABASE DCWP_ANALYTICS;

CREATE OR REPLACE DYNAMIC TABLE STAGING.DCWP_L1
TARGET_LAG = '5 minutes'
WAREHOUSE = WH_DEV
AS
SELECT
  UPPER(TRIM(BUSINESS_NAME))  AS BUSINESS_NAME,
  UPPER(TRIM(INDUSTRY))       AS INDUSTRY,
  UPPER(TRIM(COMPLAINT_TYPE)) AS COMPLAINT_TYPE,
  MEDIATION_START_DATE,
  MEDIATION_CLOSE_DATE,
  UPPER(TRIM(COMPLAINT_RESULT)) AS COMPLAINT_RESULT,
  UPPER(TRIM(SATISFACTION))     AS SATISFACTION,
  COALESCE(RESTITUTION,0) AS RESTITUTION,
  BUSINESS_CITY, BUSINESS_STATE, BUSINESS_ZIP,
  LONGITUDE, LATITUDE
FROM RAW.DCWP_COMPLAINTS;