USE ROLE DEVELOPER;
USE WAREHOUSE WH_DEV;
USE DATABASE DCWP_ANALYTICS;

CREATE OR REPLACE DYNAMIC TABLE MART.DCWP_SUMMARY
TARGET_LAG = '10 minutes'
WAREHOUSE = WH_DEV
AS
SELECT
  INDUSTRY,
  COMPLAINT_TYPE,
  DATE_TRUNC('month', MEDIATION_START_DATE) AS MONTH,
  COUNT(*) AS CNT,
  AVG(RESTITUTION) AS AVG_RESTITUTION
FROM STAGING.DCWP_L1
GROUP BY 1,2,3;
